### ISSUE TITLE
Registry Installation under Python 3.10

### ISSUE THREAD

**Issue by bobturneruk** [FAIRDataPipeline/FAIR-CLI#220]
Tried the following:

```sh
conda create -y --force -n fair
conda activate fair
conda install pip
pip install fair-cli
fair init
```

response to `fair init`:

```
Initialising FAIR repository, setup will now ask for basic info:

Error: Failed to read global configuration, re-running global setup.
Checking for local registry
Local registry found
Local Registry URL [http://127.0.0.1:8000/api/]:
Remote API URL [https://data.scrc.uk/api/]:
Remote Data Storage Root [https://data.scrc.uk/data/]:
Remote API Token File [C:\Users\bobturner\.fair\registry\remote-token]:
Local registry is offline, would you like to start it? [y/N]: y
Error: Failed to start local registry, no response from server
```

**Comment by bobturneruk** [comment]
I will look into this some more.

**Comment by RyanJField** [comment]
Hi Bob, try installing the registry from the cli: 
```
fair registry install
fair init
```

**Comment by RyanJField** [comment]
Hi Bob, how did you install the registry?

**Comment by bobturneruk** [comment]
I'm trying to use `pip` but there may be some broken stuff on my computer making this a problem specific to me, so I'm trying to figure that out.

**Comment by bobturneruk** [comment]
```
fair registry install
Error: Local registry is already installed in C:\Users\bobturner\.fair\registry
```

**Comment by RyanJField** [comment]
What happens when if you run:
```
c:\Users\bobturner\.fair\registry\scripts\start_fair_registry_windows.bat
```

**Comment by bobturneruk** [comment]
```
C:\WINDOWS\system32>c:\Users\bobturner\.fair\registry\scripts\start_fair_registry_windows.bat
curl, Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets is installed, continuing...
setting port to 8000

SUCCESS: Specified value was saved.
refreshing enviromental variables
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
Spawning Server
waiting for server to start

Waiting for 0 seconds, press a key to continue ...

Waiting for 0 seconds, press a key to continue ...

Waiting for 4 seconds, press a key to continue ...
```

**Comment by bobturneruk** [comment]
Seems like needs python 3.9 or lower, not 3.10

**Comment by RyanJField** [comment]
`fair registry install` needs to be fully tested under python 3.10

**Comment by RyanJField** [comment]
> `fair registry install` needs to be fully tested under python 3.10

@bruvio Can you test this under the CI?

**Comment by bruvio** [comment]
I tested the python api also for 3.10

@RyanJField  

https://github.com/FAIRDataPipeline/pyDataPipeline/actions/runs/1953758703

it fails for windows only (in that run installation is skipped)

**Comment by RyanJField** [comment]
> I tested the python api also for 3.10
> 
> @RyanJField
> 
> https://github.com/FAIRDataPipeline/pyDataPipeline/actions/runs/1953758703
> 
> it fails for windows only (in that run installation is skipped)

@bruvio Thanks, this needs testing with the CLI i.e., `fair registry install` under python 3.10

**Comment by bruvio** [comment]
@RyanJField @bobturneruk it seems to me that it is an issue with the registry local_requirement file. currently they are set to use lxml==4.6.3. On windows 10, python3.10.2 I managed to install locally using lxml==4.8.0

**Comment by bruvio** [comment]
please see [this update workflow](https://github.com/FAIRDataPipeline/pyDataPipeline/actions/runs/1988012504)... It-s a bit ugly but as I was not able to touch the data registry repo. I just changed the requirement on lxml to use 4.8.0 and it worked on the ci. to make it more reliable we should move the data registry to use poetry as dependencies manager.  if you run poetry add $(cat local-requirements.txt) it creates a set of dependencies that can be used across a wider python matrix. Hope it makes sense.

**Comment by RyanJField** [comment]
This make sense, I’ve added you to the data-registry repo in case you need access going forward.

**Comment by bobturneruk** [comment]
Currently can't install registry (Windows 10, Python 10, `develop` branch):

```
(fdp) PS C:\Users\bobturner\Documents\FAIR-CLI> fair registry install
Traceback (most recent call last):
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bobturner\anaconda3\envs\fdp\Scripts\fair.exe\__main__.py", line 7, in <module>
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\bobturner\Documents\FAIR-CLI\fair\cli.py", line 312, in install
    _version = fdp_svr.install_registry(
  File "C:\Users\bobturner\Documents\FAIR-CLI\fair\registry\server.py", line 363, in install_registry
    _venv.create(venv_dir)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\venv\__init__.py", line 75, in create
    self._setup_pip(context)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\venv\__init__.py", line 313, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\bobturner\\.fair\\registry\\venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 9009.
```

`feature/address_on_local` branch:

```
(fdp) PS C:\Users\bobturner\Documents\FAIR-CLI> fair registry install
Traceback (most recent call last):
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bobturner\anaconda3\envs\fdp\Scripts\fair.exe\__main__.py", line 7, in <module>
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\bobturner\Documents\FAIR-CLI\fair\cli.py", line 312, in install
    _version = fdp_svr.install_registry(
  File "C:\Users\bobturner\Documents\FAIR-CLI\fair\registry\server.py", line 363, in install_registry
    _venv.create(venv_dir)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\venv\__init__.py", line 75, in create
    self._setup_pip(context)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\venv\__init__.py", line 313, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\bobturner\anaconda3\envs\fdp\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\bobturner\\.fair\\registry\\venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 9009.
```

**Comment by bobturneruk** [comment]
This fixes it for win 10, py 10: https://stackoverflow.com/questions/58754860/cmd-opens-windows-store-when-i-type-python

It does seem strange to me that we're ending up with another copy of python being installed, but maybe that's a normal django thing.

**Comment by RyanJField** [comment]
The registry / FAIR CLI creates a virtual environment with its own python executable.

This will need fixing on windows still or a note to disable this windows feature, It must be new as my new windows laptop also needed this turning off.

**Comment by bobturneruk** [comment]
Yes, it is most frustrating, but good to know where the problem lies.

**Comment by RyanJField** [comment]
> Yes, it is most frustrating, but good to know where the problem lies.

This should be fixed with #257

**Comment by RyanJField** [comment]
@bobturneruk Please confirm this issue is now fixed.

**Comment by RyanJField** [comment]
Yes we need to update the PyPi release but it's whether or not we want to fix the push command first or not.

Also if you run a fair init --ci in a repo does the registry start then?

**Comment by bobturneruk** [comment]
I'll check. I can confirm that the above works if I use the current `develop` branch via `pip install .`.

**Comment by bobturneruk** [comment]
```
fair init --ci

Error: Failed to find local registry executable '<myuserfolder>\.fair\registry\scripts\start_fair_registry_windows.bat', is the FAIR data pipeline properly installed on this system?
```

I think 'cos it doesn't install using the cli version off PyPI, it can't init.

**Comment by RyanJField** [comment]
Fixed
