### ISSUE TITLE
`fair init --using <file.yaml>` no longer works

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#56]
Cannot find local registry uri.

**Comment by kzscisoft** [comment]
@richardreeve Do you have a traceback for this?

**Comment by richardreeve** [comment]
This was the error that we've just been discussing:
```sh
(fair-6UDMIGpx-py3.8) (base) bleaberry[~/Documents/git/julia/EcoSISTEM] fair init --using richardr.yaml --debug
FAIR repository is already initialised.
Traceback (most recent call last):
  File "/Users/richardr/tmp/FAIR-CLI/fair/configuration.py", line 289, in get_local_uri
    return _cfg['registries']['local']['uri']
KeyError: 'registries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardr/Library/Caches/pypoetry/virtualenvs/fair-6UDMIGpx-py3.8/bin/fair", line 5, in <module>
    cli()
  File "/Users/richardr/Library/Caches/pypoetry/virtualenvs/fair-6UDMIGpx-py3.8/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/richardr/Library/Caches/pypoetry/virtualenvs/fair-6UDMIGpx-py3.8/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/richardr/Library/Caches/pypoetry/virtualenvs/fair-6UDMIGpx-py3.8/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/richardr/Library/Caches/pypoetry/virtualenvs/fair-6UDMIGpx-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/richardr/Library/Caches/pypoetry/virtualenvs/fair-6UDMIGpx-py3.8/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/richardr/tmp/FAIR-CLI/fair/cli.py", line 120, in init
    raise e
  File "/Users/richardr/tmp/FAIR-CLI/fair/cli.py", line 117, in init
    fair_session.initialise(using=_use_dict, registry=registry, export_as=export)
  File "/Users/richardr/tmp/FAIR-CLI/fair/session.py", line 715, in __exit__
    self.close_session()
  File "/Users/richardr/tmp/FAIR-CLI/fair/session.py", line 610, in close_session
    _local_uri = fdp_conf.get_local_uri()
  File "/Users/richardr/tmp/FAIR-CLI/fair/configuration.py", line 291, in get_local_uri
    raise fdp_exc.CLIConfigurationError(
fair.exceptions.CLIConfigurationError: Expected key 'registries:local:uri' in local CLI configuration
```
The file was just an empty dict `{}` it turned out. Anyway, fixed in #55 I think
