### ISSUE TITLE
Error in `fair init` - Email

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#76]
```
(fair-cli-kJcAWAhH-py3.7) (base) Soniam@MacBook-Pro:~/Desktop/git/FAIRDataPipeline/rSimpleModel$ fair init
Initialising FAIR repository, setup will now ask for basic info:

Checking for local registry
Local registry found
Local Registry URL [http://localhost:8000/api/]:
Remote API URL [https://data.scrc.uk/api/]:
Remote Data Storage Root [https://data.scrc.uk/data/]:
Remote API Token File [/Users/Soniam/.fair/registry/remote-token]:
Default Data Store:  [/Users/Soniam/.fair/data/]:
Email: sonia.mitchell@glasgow.ac.uk
Traceback (most recent call last):
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/cli.py", line 120, in init
    export_as=export
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 567, in initialise
    registry
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/configuration.py", line 476, in global_config_query
    _glob_conf_dict = _get_user_info_and_namespaces()
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/configuration.py", line 335, in _get_user_info_and_namespaces
    _user_email = click.prompt("Email")
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/termui.py", line 143, in prompt_func
    return f(" ")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 14: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/bin/fair", line 5, in <module>
    cli()
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/cli.py", line 120, in init
    export_as=export
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 736, in __exit__
    self.close_session()
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 621, in close_session
    _local_uri = self._global_config['registries']['local']['uri']
KeyError: 'registries'
```

**Comment by soniamitchell** [comment]
randomly started working again
