### ISSUE TITLE
Better error when `default_input_namespace` doesn't match

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#77]
When `fair run` tries to generate a working config where the `default_input_namespace` doesn't match the data product in the registry.. it spits out a fairly long stack trace.. presumably fair run needs to check and throw an error

**Comment by soniamitchell** [comment]
Here's an example of the stack trace:
```
Updating registry from config.yaml
WARNING:FAIRDataPipeline.ConfigYAML:Remote registry pulls are not yet implemented
WARNING:FAIRDataPipeline.ConfigYAML:Remote registry pulls are not yet implemented
Traceback (most recent call last):
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/bin/fair", line 5, in <module>
    cli()
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/cli.py", line 495, in pull
    fair.run_job(mode=fdp_run.CMD_MODE.PULL)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 293, in run_job
    mode=mode
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/run.py", line 145, in run_command
    _job_cfg.prepare(_job_dir, _timestamp, mode)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/user_config.py", line 392, in prepare
    self['run_metadata.latest_commit'] = self._fetch_latest_commit()
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/user_config.py", line 230, in _fetch_latest_commit
    _repository = git.Repo(fdp_com.find_git_root(self.local_repository))
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/common.py", line 180, in find_git_root
    search_parent_directories=True
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/git/repo/base.py", line 152, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /Users/Soniam/Desktop/git/FAIRDataPipeline/rDataPipeline/local_repo
```

**Comment by soniamitchell** [comment]
Tagging you @kzscisoft incase you haven't seen this

**Comment by kzscisoft** [comment]
Your stack trace seems to actually be related to there being no such local git repository '/Users/Soniam/Desktop/git/FAIRDataPipeline/rDataPipeline/local_repo'. I am confused as to why the directory name is `local_repo` when this should be just a tag in the configuration, did you make such a location?

**Comment by soniamitchell** [comment]
Ahh right, I used an old config file. In that case all is well, you can close this issue.
