### ISSUE TITLE
`fair init` error when trying to initialise another directory with a different default input namespace

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#80]
```
Initialising FAIR repository, setup will now ask for basic info:

Local Git repository [/Users/Soniam/Desktop/git/FAIRDataPipeline/javaSimpleModel]: 
Git remote name [origin]: 
Using git repository remote 'origin': https://github.com/FAIRDataPipeline/javaSimpleModel.git
Remote API URL [https://data.scrc.uk/api/]: 
Remote API Token File [/Users/Soniam/Desktop/git/FAIRDataPipeline/rDataPipeline/token.txt]: 
Default output namespace [smitchell]: bboskamp
Default input namespace [smitchell]: bboskamp
Initialised empty fair repository in /Users/Soniam/Desktop/git/FAIRDataPipeline/javaSimpleModel/.fair

Traceback (most recent call last):
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/bin/fair", line 5, in <module>
    cli()
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/cli.py", line 120, in init
    export_as=export
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 736, in __exit__
    self.close_session()
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 634, in close_session
    _uri
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/registry/storage.py", line 351, in store_namespace
    uri, "namespace", data=_data, params={"name": namespace_label}
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/registry/requests.py", line 420, in post_else_get
    _loc = _loc[0]
IndexError: list index out of range
```

**Comment by soniamitchell** [comment]
It could be I'm forgetting to call `fair registry stop` prior to reinstalling the registry...? But this has happened a couple of times now.

**Comment by soniamitchell** [comment]
I've got the same error when calling `fair init` in a new directory and trying to set up a different default input namespace. It seemed to set up the default output namespace without any problem.

**Comment by soniamitchell** [comment]
I get this error even after calling `fair purge --global`

**Comment by soniamitchell** [comment]
`fair init --using file.yaml` works fine on multiple directories with different namespaces

**Comment by kzscisoft** [comment]
Tried this in `kzscisoft/method-compatibility-fixes` and seems to work ok
