### ISSUE TITLE
`fair registry stop` error in uninitialised directory

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#81]
Calling `fair registry stop` in a directory that hasn't been initialised results in 
```
Traceback (most recent call last):
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/bin/fair", line 5, in <module>
    cli()
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Soniam/Library/Caches/pypoetry/virtualenvs/fair-cli-kJcAWAhH-py3.7/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/cli.py", line 211, in stop
    fdp_session.FAIR(os.getcwd(), server_mode=_mode)
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/session.py", line 119, in __init__
    and not os.path.exists(fdp_com.registry_home())
  File "/Users/Soniam/Desktop/git/FAIRDataPipeline/FAIR-CLI/fair/common.py", line 53, in registry_home
    _glob_conf = yaml.safe_load(open(global_fdpconfig()))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Soniam/.fair/cli/cli-config.yaml'
```

**Comment by kzscisoft** [comment]
@soniamitchell this to me looks like you have not setup FAIR at all. It complains there is no global CLI configuration which means that `fair init` has not been run at all on the system (or it has been run and then you have removed things). 

It would only be location dependent if the state `cli-config.yaml` was the one within a repository, e.g.:

```
mkdir my_project
fair init
```
would yield:
```
my_project/.fair/cli-config.yaml
```
which would be a local CLI configuration.

**Comment by soniamitchell** [comment]
@kzscisoft This is possible. Unfortunately, a lot of the errors I was generating at this time I couldn't reproduce consistently... and so I started posting them as issues to keep a record. Whether this particular issue is related to a lack of setup or general CLI instability, it might be useful to have more informative error messages.

**Comment by kzscisoft** [comment]
@soniamitchell I always agree with more feedback to the user. 

Maybe not applicable in this case but I am aware this has not been made widely known in docs: you can use `--debug` on most commands to get more outputs and also get tracebacks as opposed to just a simple error (the idea is to mask tracebacks by default and then `--debug` can be used to get help).
